apiVersion: skaffold/v2beta6
kind: Config
deploy:
  helm:
    releases:
      - name: ingress
        chartPath: .\deployment\helm\
        valuesFiles:
          - .\deployment\helm\ingress-values.yaml
      - name: annot-service
        chartPath: .\deployment\helm\
        valuesFiles:
          - .\deployment\helm\micro-values.yaml
        artifactOverrides:
          image: cubrenig/pgwasannot-service

build:
  local:
    push: false
    concurrency: 1
  artifacts:
    - image: cubrenig/pgwasannot-service
      context: app
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
