name: deploy-annot

on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd app && docker build -t cubrenig/pgwasannot:latest -t cubrenig/pgwasannot:$GITHUB_SHA .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push cubrenig/pgwasannot:latest
      - run: docker push cubrenig/pgwasannot:$GITHUB_SHA
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder to avoid errors'
#          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files with rsync
        run: rsync -avz ${{ github.workspace }}/ ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME_DIR }}/files/dist/annot/
      - name: run script commands via ssh
        uses: appleboy/ssh-action@master
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: SHA
          script: |
            echo $SHA > ${{ secrets.HOME_DIR }}/myfile.txt
            helm upgrade annot ${{ secrets.HOME_DIR }}/files/dist/annot/dev_depl/helm/ --install --wait --set image=cubrenig/pgwasannot:$SHA --values=${{ secrets.HOME_DIR }}/files/dist/annot/dev_depl/helm/micro-values.yaml
#            helm install annot --dry-run --debug ${{ secrets.HOME_DIR }}/files/dist/annot/dev_depl/helm --set image=cubrenig/pgwasannot:latest --values=${{ secrets.HOME_DIR }}/files/dist/annot/dev_depl/helm/micro-values.yaml
#      - uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#      - run: doctl kubernetes cluster kubeconfig save k8s-1-21-2-do-2-fra-pgwas
#      - run: helm upgrade annot ./dev_depl/helm/ --install --wait --set image=cubrenig/pgwasannot:$GITHUB_SHA --values=./dev_depl/helm/micro-values.yaml
